// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evuthtibrqqeqibmskhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dXRodGlicnFxZXFpYm1za2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzAwNTEsImV4cCI6MjA3MDA0NjA1MX0._mA1aV3bciAHRaRkAu7mV0ZpKlAy5dLWwo6fUgAxSt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});